### ISSUE TITLE
Big arrays: Performance issue in proxy handler get method

### ISSUE THREAD

**Issue by reda-alaoui** [ElliotNB/observable-slim#24]
Sometimes, when I proxy an array of several multi attribute objects, ObservableSlim proxy cache ends up filled with more than 38000 proxies.
The proxy cache lookup causes performance issues on properties access (get method of the proxy handler).

Could the proxy cache be splitted by scope usages to accelerate the lookup?

**Comment by ElliotNB** [comment]
Hmm, do you have a repro example of this particular performance issue? I've used ObservableSlim on some very large datasets (an array with tens of thousands of nested multi-attribute objects) and it performed well for me -- even in IE11. Maybe you're doing something slightly different than what I've tried before.

**Comment by ElliotNB** [comment]
@reda-alaoui Just an FYI -- I'm now working on a unit test that iterates over a large array containing multi-attribute objects to establish some sort of minimal acceptable performance metrics. But if you have any repro examples of your particular issue, please let me know, thanks!

**Comment by reda-alaoui** [comment]
Hi @ElliotNB ,

Thank you for your follow up on this.
I am sorry because I currently have no time to help with an example.
I will do it ASAP.

**Comment by ElliotNB** [comment]
Yeah, I've been swamped at work too, but this issue is still on my to do list and I'll definitely be following up on it. Maintaining performance with very large data sets is a high priority for the project.
