### ISSUE TITLE
DOMinus.js

### ISSUE THREAD

**Issue by Gurigraphics** [ElliotNB/observable-slim#25]
I used **Observable-slim** to create this: 

**DOMinus.js** is a reactive data binding library that turn HTML irrelevant.
https://github.com/Gurigraphics/DOMinus.js

My code did not look great but it works. :)

Thanks for lib @ElliotNB.

**Comment by ElliotNB** [comment]
@Gurigraphics I'm glad to hear Observable-Slim was useful for your project! Thanks for the note!
