### ISSUE TITLE
Splice method not detecting addition/deletion in changes.

### ISSUE THREAD

**Issue by joharzmn** [ElliotNB/observable-slim#27]
I have this model: 
```
todos: [
          {
            id: "a81823a9-2afa-4427-963f-01693809fe0e", 
            name: "Task1",
            done: true
          },
          {
            id: "1daa7f75-9de9-4925-a94e-0169380a6efa",
            name: "Task2",
            done: false
          }
        ]
```

Here i am creating ObservableSlim like this:

```
   const proxy = ObservableSlim.create(model['todos'],  null, function(changes: any) { });
   proxy.splice(0, 1, { { id: "a81823a9-2afa-4427-963f-01693809fe0e",  name: "Task3", done: true }, });
```

**Changes I get:**
// change is something like this. But is there any way we can get the deleted and added item? 
   ```
      [ { type: 'update',
    target: [ [Object], [Object], __length: 2 ],
    property: '0',
    newValue: { name: 'Task3', done: false },
    previousValue: 
     { id: 'a81823a9-2afa-4427-963f-01693809fe0e',
       name: 'Task1',
       done: true },
    currentPath: '0',
    jsonPointer: '/0',
    proxy: [ [Object], [Object], __length: 2 ] } ]
```

**Question:**
How will I know which item is deleted and added?  The change is of type 'update' only. 

**What I need:**
It should return the deletions/additions when  use splice method.

**Comment by ElliotNB** [comment]
@joharzmn I'll take a closer look at this later today, but from what I'm seeing that's just the expected behavior for how `Proxy` reports these mutations. The first item was replaced with `{ { id: "a81823a9-2afa-4427-963f-01693809fe0e",  name: "Task3", done: true }, }`. There wasn't actually an addition or deletion performed -- just an update.

**Comment by joharzmn** [comment]
Okay @ElliotNB, I got it. Thanks for your response. 
I will close this issue but can you take a look at this issue: #28
