### ISSUE TITLE
Conditional recursive watch

### ISSUE THREAD

**Issue by clabe45** [ElliotNB/observable-slim#33]
Hello and thank you for your work! Is there a way that can watch all properties of an object, recursively, only if a property passes some test.

For instance, say I only want to watch for changes with "public properties", or properties that don't begin with `_`. I have the following object:

```js
const o = {
    _idcAboutPrivateState: { foo: 0 },
    userModifiableProperty: { bar: 0 }
};
```

In this case, only `o.userModifiableProperty` and `o.userModifiableProperty.bar` should be watched.

**Comment by BinarySpike** [comment]
The solution I'm working on for this problem is a "middleware" style solution like how ExpressJS or KoaJS work.

You probably want to do something like this:
```javascript
var p = ObservableSlim.create(test, true, function(changes) {
	if (changes.currentPath.startsWith("_") == false) {
            // handle change
        }
});
```

**Comment by clabe45** [comment]
Ah, didn't think of that, thanks :laughing:
