### ISSUE TITLE
Consider JSON Pointer

### ISSUE THREAD

**Issue by mbalex99** [ElliotNB/observable-slim#9]
Love the Library But I wonder if the path can be expressed with [JSON Pointer rfc6901](https://tools.ietf.org/html/rfc6901)?

```ts
const data = {
  name: "Max",
  age: 27,
  tags: ["a", "b", "c"],
  friends: [
    {
      name: "Adam",
      age: 27,
      tags: ["a", "b", "c"]
    },
    {
      name: "Joe",
      age: 30,
      tags: ["a", "b", "c"]
    }
  ]
}
```

If I do 

```ts
p.friends[0].tags.push('j')
```

The changes looks like:

```json
[
  {
    "type": "add",
    "target": [
      "a",
      "b",
      "c",
      "j"
    ],
    "property": "3",
    "newValue": "j",
    "currentPath": "friends.0.tags",
    "proxy": [
      "a",
      "b",
      "c",
      "j"
    ]
  }
]
```

Would it be possible that the path could be a json pointer?

**Comment by ElliotNB** [comment]
Thank you for your interest in the library! That's a great suggestion.

For backwards compatibility, I think I'll keep `currentPath` as-is for now (possibly deprecate) and add a new property for the JSON pointers.

It shouldn't take too much effort to build this enhancement -- might be able to get it published by later this evening or tomorrow.

**Comment by mbalex99** [comment]
Amazing! This is very cool!!

**Comment by ElliotNB** [comment]
@mbalex99 Took me a bit longer than expected to get around to this, but I've added support for JSON pointers as of commit d2e9e4f. The `change` object now includes a `jsonPointer` property in addition to the `currentPath`.

I've tested it out in a variety of scenarios and expanded the unit tests, but if you notice any problems please be sure to let me know! Thanks again for the suggestion.
